# Generated by Django 3.0.5 on 2023-11-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_auto_20231123_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
