# Generated by Django 3.0.5 on 2023-11-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_auto_20231123_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, upload_to='image/')),
                ('password', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
