# Generated by Django 3.0.5 on 2023-11-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_patient1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient1',
            name='password',
        ),
    ]
