# Generated by Django 3.0.5 on 2023-11-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0012_appointment_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor1', models.CharField(max_length=255, null=True)),
                ('Patient1', models.CharField(max_length=255, null=True)),
                ('Symptoms', models.CharField(max_length=255, null=True)),
                ('medicine', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
