# Generated by Django 3.0.5 on 2023-11-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0013_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='Patient_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
