# Generated by Django 3.0.5 on 2023-11-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0014_pharmacy_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment1',
            name='doctor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment1',
            name='patient',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
