# Generated by Django 3.0.5 on 2023-11-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0019_auto_20231128_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='Patient',
            new_name='Patientno',
        ),
    ]
