# Generated by Django 3.0.5 on 2023-11-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0021_auto_20231128_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment1',
            name='patientno',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
