# Generated by Django 3.0.5 on 2023-11-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0022_appointment1_patientno'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patientno',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
